### ISSUE TITLE
wrench.js is deprecated

### ISSUE THREAD

**Issue by george-i** [linemanjs/lineman-bower#10]
`npm WARN deprecated wrench@1.4.4: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.`

I'm not sure how it affects the functionality.

**Comment by searls** [comment]
If you're using the repo, feel free to send a PR to update deps if you've tested it.
