### ISSUE TITLE
lineman-bower does not copy dependencies by default

### ISSUE THREAD

**Issue by campbell** [linemanjs/lineman-bower#7]
By default, `lineman-bower` will not copy new dependencies into the `/vendor/bower`. I'm not a Bower expert, but I thought that `lineman-bower` would let me specify JS dependencies and have them automatically included in my Lineman app...but it doesn't by default. Why? Am I overlooking some other use case for Bower?

https://github.com/linemanjs/lineman-bower/blob/master/config/plugins/bower.coffee#L18

```
bower:
   install:
     options:
       copy: false
```

To install dependencies with Bower, I had to override this config in `/config/application.js`. 

At the very least, the documentation should be updated to mention this behavior and how to override it (and yes, I am volunteering to update the docs if this is an appropriate solution).

**Comment by jayharris** [comment]
Correct. `lineman-bower` does not automatically include the files into your application. A `bower` package could be a JavaScript file, Sass file, LESS, CoffeeScript, CSS, or many more, and there is no standardized specification for what the distributable files are, their filename, or where they live in the package's folder structure.. Because of this, you must manually specify which file to be included into your application.

`lineman-bower` will only ensure that the package is downloaded and available.

**Comment by campbell** [comment]
Are you referring to how the files get compiled into the app, or that they should not be automatically copied into `/vendor/bower`? I understand why `files.js` would not automatically be updated, but copying the dependency into `vendor/bower` seems harmless.

(and thanks for the really fast reply, much appreciated)

**Comment by campbell** [comment]
"`lineman-bower` will only ensure that the package is downloaded and available."

Where does it get downloaded? I added D3 as a dependency & ran `lineman build` but I don't know where the D3 files are? `bower list` shows D3 as not installed.

**Comment by jayharris** [comment]
I am referring to how files get copied into the app; you would need to update `files.js` for that. However, the files should automatically be downloaded in to `vendor/bower` as a part of `lineman run` or `lineman build`, as long as the packages are referenced in `bower.json`.

`copy: false` has nothing to do with getting files into `vendor\bower`. That is for copying package contents to a separate target directory--such as `app\js`--but `lineman` does not use this (because of the reasons specified before).

How did you add the D3 dependency?

**Comment by campbell** [comment]
I added the D3 dependency via `bower.json`:

```
{
  "name": "my-app",
  "version": "0.0.1",
  "dependencies": {
    "jquery": "~1.9.0",
    "d3": ""
  }
}
```

**Comment by jayharris** [comment]
Is `jquery` in `vendor/bower`? Do you have a `.bowerrc` file?

**Comment by campbell** [comment]
I have a `.bowerrc` file: 

```
{
  "directory": "/vendor/bower"
}
```

**Comment by jayharris** [comment]
Does it list a directory property? The directory in your `.bowerrc` file always wins, overriding the `lineman` directory configuration.

**Comment by campbell** [comment]
I had `jquery` in `vendor/bower` when I started. I was trying to add `moment` (momentjs) via Bower but it never was copied into `vendor/bower` until I overrode `copy:true`. However, now I have deleted both `jquery` and `moment` from `vendor/bower` and `lineman build` does not restore them.

**Comment by campbell** [comment]
The directory in `.bowerrc` is `/vendor/bower` (I sent the original reply too soon, before I could add that context).

**Comment by campbell** [comment]
`lineman build` shows a `clean:bower` task but no other Bower tasks - should I be seeing something else here?

**Comment by jayharris** [comment]
`lineman build` should show `clean:bower` and `bower:install`. I've tried a new application--`lineman new`--using your `bower.json`, and both `jquery` and `d3` appear in `vendor/bower` as expected.

Have you made any other customizations to the configuration? What version of `lineman` and `lineman-bower` are you using? Can you add in your entire `.bowerrc`?

**Comment by campbell** [comment]
Argh, this was self-inflicted. I had a `prependTasks.common` setting that overwrote the tasks instead of appending, thus the `lineman-bower` prependTasks were removed.

```
prependTasks: {
      common: ["copy-environment-config-file"]
    },
```

should have been

```
prependTasks: {
      common: ["copy-environment-config-file"].concat(lineman.config.application.prependTasks.common)  // Copy the appropriate app/config/*.js file for the environment
    }
```

Sorry for the trouble, I do appreciate the help.

**Comment by jayharris** [comment]
No worries. Sometimes we all just need a Cardboard Cutout to talk out an issue. Glad it's figured out.
Cheers.

**Comment by campbell** [comment]
Next time I'll talk to my RailsGirls rubber duck...but you did confirm that my app was misbehaving, which was very helpful.

**Comment by jasonkarns** [comment]
FWIW, we're aware that the api for prependTasks, appendTasks and removeTasks needs improvement. But no movement has yet been made on an improvement. :)
